In [251]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score

from sklearn.ensemble import (
    GradientBoostingClassifier,
    RandomForestClassifier
)
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

from sklearn.preprocessing import StandardScaler

In [200]:
RANDOM_STATE = 777

In [201]:
test = pd.read_csv(
    filepath_or_buffer="test.csv"
)

train = pd.read_csv(
    filepath_or_buffer="train.csv"
)

In [202]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1000 non-null   int64
 1   battery_power  1000 non-null   int64
 2   blue           1000 non-null   int64
 3   clock_speed    1000 non-null   float64
 4   dual_sim       1000 non-null   int64
 5   fc             1000 non-null   int64
 6   four_g         1000 non-null   int64
 7   int_memory     1000 non-null   int64
 8   m_dep          1000 non-null   float64
 9   mobile_wt      1000 non-null   int64
 10  n_cores        1000 non-null   int64
 11  pc             1000 non-null   int64
 12  px_height      1000 non-null   int64
 13  px_width       1000 non-null   int64
 14  ram            1000 non-null   int64
 15  sc_h           1000 non-null   int64
 16  sc_w           1000 non-null   int64
 17  talk_time      1000 non-null   int64
 18  three_g        1000 non-null   int64
 19  touch_screen   1000 non-null   int64
 20  wifi           1000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 164.2 KB

In [203]:
if len(test[test["id"].duplicated()]) >= 1:
    print("There is at least 1 duplicate row")
else:
    print("No duplicates")

No duplicates

In [204]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  2000 non-null   int64
 1   blue           2000 non-null   int64
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64
 4   fc             2000 non-null   int64
 5   four_g         2000 non-null   int64
 6   int_memory     2000 non-null   int64
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64
 9   n_cores        2000 non-null   int64
 10  pc             2000 non-null   int64
 11  px_height      2000 non-null   int64
 12  px_width       2000 non-null   int64
 13  ram            2000 non-null   int64
 14  sc_h           2000 non-null   int64
 15  sc_w           2000 non-null   int64
 16  talk_time      2000 non-null   int64
 17  three_g        2000 non-null   int64
 18  touch_screen   2000 non-null   int64
 19  wifi           2000 non-null   int64
 20  price_range    2000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 328.3 KB

In [205]:
if (test.dtypes.equals(train.dtypes)) and (test.columns.equals(train.columns)):
    print("EQUAL columns and data types")

In [206]:
train["price_range"].value_counts()

price_range
1    500
2    500
3    500
0    500
Name: count, dtype: int64

Due to the fact that we do not have `price_range`s in our `test.csv`, I will extract random 200 rows from `train.csv` which will be used for model evaluation. Shortage of data...

In [207]:
records_table = pd.DataFrame()
def add_to_records_table(
    records_table: pd.DataFrame, 
    model_name: str,
    model_accuracy
    ) -> None:

    records_table.loc[len(records_table), "model_name"] = model_name
    records_table.loc[len(records_table) - 1, "model_accuracy"] = model_accuracy

In [208]:
X = train.drop(columns="price_range")
y = train["price_range"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.1  # Exactly 200 rows for testing. Nothing more nor less
)

### Gradient Boosting Classifier

In [209]:
gradient_boosting = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    subsample=0.8
)

gradient_boosting.fit(X_train, y_train)

GradientBoostingClassifier(learning_rate=0.05, n_estimators=200, subsample=0.8)

In [210]:
y_pred = gradient_boosting.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.915

In [211]:
add_to_records_table(
    records_table=records_table,
    model_name="Gradient Boosting Classifier",
    model_accuracy=accuracy)

#### Random Gradient Boosting Classifier

In [212]:
param_gb = {
    "n_estimators": np.arange(100, 500, 50),
    "learning_rate": np.logspace(-3, -1, 20),
    "max_depth": np.arange(3, 8)
}

In [213]:
random_gradient = GradientBoostingClassifier()

random_gradient_boosting = RandomizedSearchCV(
    random_gradient,
    param_distributions=param_gb,
    n_iter=30,                       # number of random combos
    cv=5,
    scoring="accuracy",
    n_jobs=-1,
    verbose=2
)

print("Random Gradient Boosting...")
random_gradient_boosting.fit(X_train, y_train)

Random Gradient Boosting...
Fitting 5 folds for each of 30 candidates, totalling 150 fits

RandomizedSearchCV(cv=5, estimator=GradientBoostingClassifier(), n_iter=30,
                   n_jobs=-1,
                   param_distributions={'learning_rate': array([0.001     , 0.00127427, 0.00162378, 0.00206914, 0.00263665,
       0.00335982, 0.00428133, 0.00545559, 0.00695193, 0.00885867,
       0.01128838, 0.0143845 , 0.01832981, 0.02335721, 0.02976351,
       0.0379269 , 0.0483293 , 0.06158482, 0.078476  , 0.1       ]),
                                        'max_depth': array([3, 4, 5, 6, 7]),
                                        'n_estimators': array([100, 150, 200, 250, 300, 350, 400, 450])},
                   scoring='accuracy', verbose=2)

In [214]:
print("Best parameters for Random Gradient Boosting:", random_gradient_boosting.best_params_)

Best parameters for Random Gradient Boosting: {'n_estimators': np.int64(400), 'max_depth': np.int64(5), 'learning_rate': np.float64(0.07847599703514611)}

In [215]:
y_pred = random_gradient_boosting.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.885

In [216]:
random_gradient_boosting = GradientBoostingClassifier(
    n_estimators=450,
    max_depth=3,
    learning_rate=np.float64(0.04832930238571752)
)

print("Random Gradient Boosting...")
random_gradient_boosting.fit(X_train, y_train)

Random Gradient Boosting...

GradientBoostingClassifier(learning_rate=np.float64(0.04832930238571752),
                           n_estimators=450)

In [217]:
y_pred = random_gradient_boosting.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.89

In [218]:
importances = random_gradient_boosting.feature_importances_
feature_importance = pd.Series(importances, index=X_train.columns)
feature_importance = feature_importance.sort_values(ascending=False)

print(feature_importance)

ram              0.796033
battery_power    0.106816
px_height        0.048660
px_width         0.029981
mobile_wt        0.005342
int_memory       0.003293
m_dep            0.002231
sc_w             0.001681
fc               0.001369
n_cores          0.001269
pc               0.000903
talk_time        0.000867
sc_h             0.000664
clock_speed      0.000288
three_g          0.000156
four_g           0.000149
wifi             0.000120
blue             0.000084
dual_sim         0.000062
touch_screen     0.000035
dtype: float64

In [219]:
important_features = feature_importance[feature_importance > 0.002].index  # Now it is only 11 features

X_train_selected = X_train[important_features]
X_test_selected  = X_test[important_features]

random_gradient_boosting = GradientBoostingClassifier(
    n_estimators=450,
    max_depth=5,
    learning_rate=np.float64(0.023357214690901212)
)

print("Random Gradient Boosting...")
random_gradient_boosting.fit(X_train_selected, y_train)

Random Gradient Boosting...

GradientBoostingClassifier(learning_rate=np.float64(0.023357214690901212),
                           max_depth=5, n_estimators=450)

In [220]:
y_pred = random_gradient_boosting.predict(X_test_selected)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9

Accuracy did not change significantly yet our model become less complex and easier to interpret. Well done!

In [221]:
important_features = feature_importance[feature_importance > 0.0033].index # Now it is only 8 features

X_train_selected = X_train[important_features]
X_test_selected  = X_test[important_features]

random_gradient_boosting = GradientBoostingClassifier(
    n_estimators=450,
    max_depth=5,
    learning_rate=np.float64(0.023357214690901212)
)

print("Random Gradient Boosting...")
random_gradient_boosting.fit(X_train_selected, y_train)

Random Gradient Boosting...

GradientBoostingClassifier(learning_rate=np.float64(0.023357214690901212),
                           max_depth=5, n_estimators=450)

In [222]:
y_pred = random_gradient_boosting.predict(X_test_selected)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.905

There still a room for better optimization. Let's remove another 2 features.

In [223]:
important_features = feature_importance[feature_importance > 0.0035].index # Now it is only 8 features

X_train_selected = X_train[important_features]
X_test_selected  = X_test[important_features]

random_gradient_boosting = GradientBoostingClassifier(
    n_estimators=450,
    max_depth=5,
    learning_rate=np.float64(0.023357214690901212)
)

print("Random Gradient Boosting...")
random_gradient_boosting.fit(X_train_selected, y_train)

Random Gradient Boosting...

GradientBoostingClassifier(learning_rate=np.float64(0.023357214690901212),
                           max_depth=5, n_estimators=450)

In [224]:
y_pred = random_gradient_boosting.predict(X_test_selected)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.905

That will be enough.

In [225]:
add_to_records_table(
    records_table=records_table,
    model_name="Optimized Random Gradient Boosting Classifier",
    model_accuracy=accuracy
)

In [226]:
records_table

                                      model_name  model_accuracy
0                   Gradient Boosting Classifier           0.915
1  Optimized Random Gradient Boosting Classifier           0.905

### Random Forest Classifier

In [227]:
random_forest_classifier = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features="sqrt",
    n_jobs=-1,
    random_state=RANDOM_STATE
)

random_forest_classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=777)

In [228]:
y_pred = random_forest_classifier.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.875

In [229]:
add_to_records_table(
    records_table=records_table,
    model_name="Random Forest Classifier",
    model_accuracy=accuracy
)

#### Randomized Search of Hyperparameters for Random Forest Classifier

In [230]:
param_forest = {
    "n_estimators": [100, 200, 300, 400],
    "max_depth": [None, 5, 10],
    "min_samples_split": list(range(2, 6)),
    "min_samples_leaf": list(range(1, 4)),
    "max_features": ["sqrt", "log2", None]
}

random_forest_classifier = RandomForestClassifier()

randomized_forest_classifier = RandomizedSearchCV(
    random_forest_classifier,
    param_distributions=param_forest,
    n_iter=30,                       # number of random combos
    cv=5,
    scoring="accuracy",
    n_jobs=-1,
    random_state=RANDOM_STATE
)

In [231]:
print("Randomized Random Forest Classifier...")
randomized_forest_classifier.fit(X_train, y_train)

Randomized Random Forest Classifier...

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_iter=30,
                   n_jobs=-1,
                   param_distributions={'max_depth': [None, 5, 10],
                                        'max_features': ['sqrt', 'log2', None],
                                        'min_samples_leaf': [1, 2, 3],
                                        'min_samples_split': [2, 3, 4, 5],
                                        'n_estimators': [100, 200, 300, 400]},
                   random_state=777, scoring='accuracy')

In [232]:
print("Best params:", randomized_forest_classifier.best_params_)

Best params: {'n_estimators': 400, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': None, 'max_depth': None}

In [233]:
y_pred = randomized_forest_classifier.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.89

In [234]:
randomized_forest_classifier = RandomForestClassifier(
    n_estimators=200,
    min_samples_split=5,
    min_samples_leaf=3,
    max_features=None,
    max_depth=10,
    random_state=RANDOM_STATE,
    n_jobs=-1
)

print("Randomized Random Forest Classifier...")
randomized_forest_classifier.fit(X_train, y_train)

Randomized Random Forest Classifier...

RandomForestClassifier(max_depth=10, max_features=None, min_samples_leaf=3,
                       min_samples_split=5, n_estimators=200, n_jobs=-1,
                       random_state=777)

In [235]:
y_pred = randomized_forest_classifier.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.89

In [236]:
importances = randomized_forest_classifier.feature_importances_
feature_importance = pd.Series(importances, index=X_train.columns)
feature_importance = feature_importance.sort_values(ascending=False)

print(feature_importance)

ram              0.663279
battery_power    0.129800
px_height        0.078657
px_width         0.077754
mobile_wt        0.011075
int_memory       0.006136
pc               0.004553
talk_time        0.004341
m_dep            0.003967
clock_speed      0.003583
sc_h             0.003473
fc               0.003412
sc_w             0.003324
n_cores          0.003130
touch_screen     0.000630
blue             0.000625
wifi             0.000613
four_g           0.000610
dual_sim         0.000600
three_g          0.000438
dtype: float64

In [237]:
important_features = feature_importance[feature_importance > 0.0045].index # Now it is only 7 features

X_train_selected = X_train[important_features]
X_test_selected  = X_test[important_features]

randomized_forest_classifier = RandomForestClassifier(
    n_estimators=200,
    min_samples_split=5,
    min_samples_leaf=3,
    max_features=None,
    max_depth=10,
    random_state=RANDOM_STATE,
    n_jobs=-1
)

print("Randomized Random Forest Classifier...")
randomized_forest_classifier.fit(X_train, y_train)

y_pred = randomized_forest_classifier.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Randomized Random Forest Classifier...
Accuracy: 0.89

In [238]:
add_to_records_table(
    records_table=records_table,
    model_name="Optimized Randomized Random Forest Classifier",
    model_accuracy=accuracy
)

In [239]:
records_table

                                      model_name  model_accuracy
0                   Gradient Boosting Classifier           0.915
1  Optimized Random Gradient Boosting Classifier           0.905
2                       Random Forest Classifier           0.905
3  Optimized Randomized Random Forest Classifier           0.905

### Logistic Regression

In [240]:
X = train.drop(columns="price_range")
y = train["price_range"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=200,
    random_state=42
)

In [241]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)   # ← transform only!

In [242]:
logistic_regression = LogisticRegression(
    C=0.7,
    solver="lbfgs",
    max_iter=5000,
    l1_ratio=0  
)

logistic_regression.fit(X_train_scaled, y_train)

LogisticRegression(C=0.7, l1_ratio=0, max_iter=5000)

In [243]:
y_pred = logistic_regression.predict(X_test_scaled)  
  
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.985

In [244]:
add_to_records_table(
    records_table=records_table,
    model_name="Logistic Regression",
    model_accuracy=accuracy
)

#### Random Logistic Regression

In [245]:
param_grid = {
    "C": np.linspace(start=0.001, stop=1, num=30),
    "solver": ['lbfgs', 'newton-cg', 'newton-cholesky', 'sag', 'saga'],
    "max_iter": [num for num in range(100, 5000, 250)]
}

random_logistic_regression = RandomizedSearchCV(
    estimator=LogisticRegression(),
    param_distributions=param_grid,
    n_iter=20,           # number of random combinations
    cv=5,
    scoring="accuracy",
    random_state=RANDOM_STATE,
    n_jobs=-1
)

random_logistic_regression.fit(X_train_scaled, y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20, n_jobs=-1,
                   param_distributions={'C': array([0.001     , 0.03544828, 0.06989655, 0.10434483, 0.1387931 ,
       0.17324138, 0.20768966, 0.24213793, 0.27658621, 0.31103448,
       0.34548276, 0.37993103, 0.41437931, 0.44882759, 0.48327586,
       0.51772414, 0.55217241, 0.58662069, 0.62106897, 0.65551724,
       0.68996552, 0.72441379, 0.75886207, 0.79331034, 0.82775862,
       0.8622069 , 0.89665517, 0.93110345, 0.96555172, 1.        ]),
                                        'max_iter': [100, 350, 600, 850, 1100,
                                                     1350, 1600, 1850, 2100,
                                                     2350, 2600, 2850, 3100,
                                                     3350, 3600, 3850, 4100,
                                                     4350, 4600, 4850],
                                        'solver': ['lbfgs', 'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   random_state=777, scoring='accuracy')

In [246]:
print("Best Parameters:", random_logistic_regression.best_params_)
best_logistic_regression = random_logistic_regression.best_estimator_

y_pred_random = best_logistic_regression.predict(X_test_scaled)
print("Test Accuracy:", accuracy_score(y_test, y_pred_random))

Best Parameters: {'solver': 'newton-cholesky', 'max_iter': 4100, 'C': np.float64(1.0)}
Test Accuracy: 0.985

#### Making Logistic Regression Less Complex

In [247]:
importances = np.abs(best_logistic_regression.coef_[0])

feature_importance = pd.Series(importances, index=X_train.columns)
feature_importance = feature_importance.sort_values(ascending=False)

print(feature_importance)

ram              11.297299
battery_power     2.834801
px_height         1.648475
px_width          1.627377
mobile_wt         0.389478
int_memory        0.173687
wifi              0.137651
clock_speed       0.105503
fc                0.101309
dual_sim          0.093966
touch_screen      0.075072
three_g           0.049340
n_cores           0.048268
sc_w              0.042749
talk_time         0.041741
m_dep             0.033173
four_g            0.018216
pc                0.017015
sc_h              0.014485
blue              0.007248
dtype: float64

In [248]:
important_features = feature_importance[feature_importance > 0.15].index # Only 6 features

X_train_selected = X_train[important_features]
X_test_selected  = X_test[important_features]

# Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_selected)
X_test_scaled = scaler.transform(X_test_selected)   # ← transform only!

logistic_regression = LogisticRegression(
    C=np.float64(0.965551724137931),
    max_iter=3100, 
    solver='sag'
)

print("Randomized Logistic Regression...")
logistic_regression.fit(X_train_scaled, y_train)

y_pred = logistic_regression.predict(X_test_scaled)
optimized_random_logistic_regression_accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", optimized_random_logistic_regression_accuracy)

Randomized Logistic Regression...
Accuracy: 0.995

In [249]:
add_to_records_table(
    records_table=records_table,
    model_name="Optimized Random Logistic Regression",
    model_accuracy=optimized_random_logistic_regression_accuracy
)

In [250]:
records_table

                                      model_name  model_accuracy
0                   Gradient Boosting Classifier           0.915
1  Optimized Random Gradient Boosting Classifier           0.905
2                       Random Forest Classifier           0.905
3  Optimized Randomized Random Forest Classifier           0.905
4                            Logistic Regression           0.905
5           Optimized Random Logistic Regression           0.995

### KNN Classifier

In [264]:
X = train.drop(columns="price_range")
y = train["price_range"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=200  # Exactly 200 rows for testing. Nothing more nor less
)

KNN uses distance metrics, so features must be scaled.

In [265]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [266]:
knn = KNeighborsClassifier(n_neighbors=5)  # default 5 neighbors
knn.fit(X_train_scaled, y_train)

y_pred = knn.predict(X_test_scaled)
knn_accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", knn_accuracy)

Accuracy: 0.495

In [267]:
add_to_records_table(
    records_table=records_table,
    model_name="Classic KNN",
    model_accuracy=knn_accuracy
)

#### Randomized Search of Hyperparameters for KNN

In [268]:
param_grid = {
    "n_neighbors": list(range(3, 25)),
    "weights": ["uniform", "distance"],
    "p": [1, 2],
    "algorithm": ['auto', 'ball_tree', 'kd_tree', 'brute']
}

random_knn = RandomizedSearchCV(
    estimator=KNeighborsClassifier(),
    param_distributions=param_grid,
    n_iter=20,                        # number of random combinations
    cv=5,
    scoring="accuracy",
    random_state=RANDOM_STATE,
    n_jobs=-1
)

random_knn.fit(X_train_scaled, y_train)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(), n_iter=20, n_jobs=-1,
                   param_distributions={'algorithm': ['auto', 'ball_tree',
                                                      'kd_tree', 'brute'],
                                        'n_neighbors': [3, 4, 5, 6, 7, 8, 9, 10,
                                                        11, 12, 13, 14, 15, 16,
                                                        17, 18, 19, 20, 21, 22,
                                                        23, 24],
                                        'p': [1, 2],
                                        'weights': ['uniform', 'distance']},
                   random_state=777, scoring='accuracy')

In [270]:
print("Best Parameters (Random):", random_knn.best_params_)

best_knn = random_knn.best_estimator_
y_pred_random = best_knn.predict(X_test_scaled)
random_knn_accuracy = accuracy_score(y_test, y_pred_random)
print("Accuracy:", random_knn_accuracy)

Best Parameters (Random): {'weights': 'distance', 'p': 1, 'n_neighbors': 23, 'algorithm': 'kd_tree'}
Accuracy: 0.675

In [272]:
add_to_records_table(
    records_table=records_table,
    model_name="Random KNN",
    model_accuracy=random_knn_accuracy
)

In [273]:
records_table

                                      model_name  model_accuracy
0                   Gradient Boosting Classifier           0.915
1  Optimized Random Gradient Boosting Classifier           0.905
2                       Random Forest Classifier           0.905
3  Optimized Randomized Random Forest Classifier           0.905
4                            Logistic Regression           0.905
5           Optimized Random Logistic Regression           0.995
6                                    Classic KNN           0.495
7                                    Classic KNN           0.495
8                                     Random KNN           0.675