In [103]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score

from sklearn.ensemble import (
    GradientBoostingClassifier,
    RandomForestClassifier
)

from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

import matplotlib.pyplot as plt

In [127]:
RANDOM_STATE = 777

In [104]:
test = pd.read_csv(
    filepath_or_buffer="test.csv"
)

train = pd.read_csv(
    filepath_or_buffer="train.csv"
)

In [105]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1000 non-null   int64
 1   battery_power  1000 non-null   int64
 2   blue           1000 non-null   int64
 3   clock_speed    1000 non-null   float64
 4   dual_sim       1000 non-null   int64
 5   fc             1000 non-null   int64
 6   four_g         1000 non-null   int64
 7   int_memory     1000 non-null   int64
 8   m_dep          1000 non-null   float64
 9   mobile_wt      1000 non-null   int64
 10  n_cores        1000 non-null   int64
 11  pc             1000 non-null   int64
 12  px_height      1000 non-null   int64
 13  px_width       1000 non-null   int64
 14  ram            1000 non-null   int64
 15  sc_h           1000 non-null   int64
 16  sc_w           1000 non-null   int64
 17  talk_time      1000 non-null   int64
 18  three_g        1000 non-null   int64
 19  touch_screen   1000 non-null   int64
 20  wifi           1000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 164.2 KB

In [106]:
if len(test[test["id"].duplicated()]) >= 1:
    print("There is at least 1 duplicate row")
else:
    print("No duplicates")

No duplicates

In [107]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  2000 non-null   int64
 1   blue           2000 non-null   int64
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64
 4   fc             2000 non-null   int64
 5   four_g         2000 non-null   int64
 6   int_memory     2000 non-null   int64
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64
 9   n_cores        2000 non-null   int64
 10  pc             2000 non-null   int64
 11  px_height      2000 non-null   int64
 12  px_width       2000 non-null   int64
 13  ram            2000 non-null   int64
 14  sc_h           2000 non-null   int64
 15  sc_w           2000 non-null   int64
 16  talk_time      2000 non-null   int64
 17  three_g        2000 non-null   int64
 18  touch_screen   2000 non-null   int64
 19  wifi           2000 non-null   int64
 20  price_range    2000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 328.3 KB

In [108]:
if (test.dtypes.equals(train.dtypes)) and (test.columns.equals(train.columns)):
    print("EQUAL columns and data types")

In [109]:
train["price_range"].value_counts()

price_range
1    500
2    500
3    500
0    500
Name: count, dtype: int64

Due to the fact that we do not have `price_range`s in our `test.csv`, I will extract random 200 rows from `train.csv` which will be used for model evaluation. Shortage of data...

In [110]:
records_table = pd.DataFrame()
def add_to_records_table(
    records_table: pd.DataFrame, 
    model_name: str,
    model_accuracy
    ) -> None:

    records_table.loc[len(records_table), "model_name"] = model_name
    records_table.loc[len(records_table) - 1, "model_accuracy"] = model_accuracy

In [111]:
X = train.drop(columns="price_range")
y = train["price_range"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.1  # Exactly 200 rows for testing. Nothing more nor less
)

### Gradient Boosting Classifier

In [73]:
gradient_boosting = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    subsample=0.8
)

gradient_boosting.fit(X_train, y_train)

GradientBoostingClassifier(learning_rate=0.05, n_estimators=200, subsample=0.8)

In [74]:
y_pred = gradient_boosting.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.905

In [75]:
add_to_records_table(
    records_table=records_table,
    model_name="Gradient Boosting Classifier",
    model_accuracy=accuracy)

#### Random Gradient Boosting Classifier

In [76]:
param_gb = {
    "n_estimators": np.arange(100, 500, 50),
    "learning_rate": np.logspace(-3, -1, 20),
    "max_depth": np.arange(3, 8)
}

In [77]:
random_gradient = GradientBoostingClassifier()

random_gradient_boosting = RandomizedSearchCV(
    random_gradient,
    param_distributions=param_gb,
    n_iter=30,                       # number of random combos
    cv=5,
    scoring="accuracy",
    n_jobs=-1,
    verbose=2
)

print("Random Gradient Boosting...")
random_gradient_boosting.fit(X_train, y_train)

Random Gradient Boosting...
Fitting 5 folds for each of 30 candidates, totalling 150 fits

RandomizedSearchCV(cv=5, estimator=GradientBoostingClassifier(), n_iter=30,
                   n_jobs=-1,
                   param_distributions={'learning_rate': array([0.001     , 0.00127427, 0.00162378, 0.00206914, 0.00263665,
       0.00335982, 0.00428133, 0.00545559, 0.00695193, 0.00885867,
       0.01128838, 0.0143845 , 0.01832981, 0.02335721, 0.02976351,
       0.0379269 , 0.0483293 , 0.06158482, 0.078476  , 0.1       ]),
                                        'max_depth': array([3, 4, 5, 6, 7]),
                                        'n_estimators': array([100, 150, 200, 250, 300, 350, 400, 450])},
                   scoring='accuracy', verbose=2)

In [78]:
print("Best parameters for Random Gradient Boosting:", random_gradient_boosting.best_params_)

Best parameters for Random Gradient Boosting: {'n_estimators': np.int64(450), 'max_depth': np.int64(3), 'learning_rate': np.float64(0.04832930238571752)}

In [79]:
y_pred = random_gradient_boosting.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.895

In [91]:
random_gradient_boosting = GradientBoostingClassifier(
    n_estimators=450,
    max_depth=3,
    learning_rate=np.float64(0.04832930238571752)
)

print("Random Gradient Boosting...")
random_gradient_boosting.fit(X_train, y_train)

Random Gradient Boosting...

GradientBoostingClassifier(learning_rate=np.float64(0.04832930238571752),
                           n_estimators=450)

In [92]:
y_pred = random_gradient_boosting.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.895

In [93]:
importances = random_gradient_boosting.feature_importances_
feature_importance = pd.Series(importances, index=X_train.columns)
feature_importance = feature_importance.sort_values(ascending=False)

print(feature_importance)

ram              0.797434
battery_power    0.105069
px_height        0.046906
px_width         0.028724
mobile_wt        0.006661
int_memory       0.004238
n_cores          0.002869
m_dep            0.001629
talk_time        0.001516
sc_w             0.001193
pc               0.001012
sc_h             0.000690
fc               0.000513
blue             0.000397
wifi             0.000382
clock_speed      0.000308
touch_screen     0.000220
three_g          0.000103
four_g           0.000073
dual_sim         0.000063
dtype: float64

In [94]:
important_features = feature_importance[feature_importance > 0.002].index  # Now it is only 11 features

X_train_selected = X_train[important_features]
X_test_selected  = X_test[important_features]

random_gradient_boosting = GradientBoostingClassifier(
    n_estimators=450,
    max_depth=5,
    learning_rate=np.float64(0.023357214690901212)
)

print("Random Gradient Boosting...")
random_gradient_boosting.fit(X_train_selected, y_train)

Random Gradient Boosting...

GradientBoostingClassifier(learning_rate=np.float64(0.023357214690901212),
                           max_depth=5, n_estimators=450)

In [95]:
y_pred = random_gradient_boosting.predict(X_test_selected)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.91

Accuracy did not change significantly yet our model become less complex and easier to interpret. Well done!

In [96]:
important_features = feature_importance[feature_importance > 0.0033].index # Now it is only 8 features

X_train_selected = X_train[important_features]
X_test_selected  = X_test[important_features]

random_gradient_boosting = GradientBoostingClassifier(
    n_estimators=450,
    max_depth=5,
    learning_rate=np.float64(0.023357214690901212)
)

print("Random Gradient Boosting...")
random_gradient_boosting.fit(X_train_selected, y_train)

Random Gradient Boosting...

GradientBoostingClassifier(learning_rate=np.float64(0.023357214690901212),
                           max_depth=5, n_estimators=450)

In [97]:
y_pred = random_gradient_boosting.predict(X_test_selected)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.91

There still a room for better optimization. Let's remove another 2 features.

In [98]:
important_features = feature_importance[feature_importance > 0.0035].index # Now it is only 8 features

X_train_selected = X_train[important_features]
X_test_selected  = X_test[important_features]

random_gradient_boosting = GradientBoostingClassifier(
    n_estimators=450,
    max_depth=5,
    learning_rate=np.float64(0.023357214690901212)
)

print("Random Gradient Boosting...")
random_gradient_boosting.fit(X_train_selected, y_train)

Random Gradient Boosting...

GradientBoostingClassifier(learning_rate=np.float64(0.023357214690901212),
                           max_depth=5, n_estimators=450)

In [99]:
y_pred = random_gradient_boosting.predict(X_test_selected)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.905

That will be enough.

In [100]:
add_to_records_table(
    records_table=records_table,
    model_name="Optimized Random Gradient Boosting Classifier",
    model_accuracy=accuracy
)

In [101]:
records_table

                                      model_name  model_accuracy
0                   Gradient Boosting Classifier           0.905
1  Optimized Random Gradient Boosting Classifier           0.915
2  Optimized Random Gradient Boosting Classifier           0.905

### Random Forest Classifier

In [144]:
random_forest_classifier = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features="sqrt",
    n_jobs=-1,
    random_state=RANDOM_STATE
)

random_forest_classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=777)

In [117]:
y_pred = random_forest_classifier.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.89

In [118]:
add_to_records_table(
    records_table=records_table,
    model_name="Random Forest Classifier",
    model_accuracy=accuracy
)

#### Randomized Search of Hyperparameters for Random Forest Classifier

In [ ]:
param_forest = {
    "n_estimators": [100, 200, 300, 400],
    "max_depth": [None, 5, 10],
    "min_samples_split": list(range(2, 6)),
    "min_samples_leaf": list(range(1, 4)),
    "max_features": ["sqrt", "log2", None]
}

random_forest_classifier = RandomForestClassifier()

randomized_forest_classifier = RandomizedSearchCV(
    random_forest_classifier,
    param_distributions=param_forest,
    n_iter=30,                       # number of random combos
    cv=5,
    scoring="accuracy",
    n_jobs=-1,
    random_state=RANDOM_STATE
)

In [123]:
print("Randomized Random Forest Classifier...")
randomized_forest_classifier.fit(X_train, y_train)

Randomized Random Forest Classifier...

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_iter=30,
                   n_jobs=-1,
                   param_distributions={'max_depth': [None, 5, 10],
                                        'max_features': ['sqrt', 'log2', None],
                                        'min_samples_leaf': [1, 2, 3],
                                        'min_samples_split': [2, 3, 4, 5],
                                        'n_estimators': [100, 200, 300, 400]},
                   random_state=777, scoring='accuracy')

In [124]:
print("Best params:", randomized_forest_classifier.best_params_)

Best params: {'n_estimators': 200, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': None, 'max_depth': 10}

In [125]:
y_pred = randomized_forest_classifier.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.895

In [128]:
randomized_forest_classifier = RandomForestClassifier(
    n_estimators=200,
    min_samples_split=5,
    min_samples_leaf=3,
    max_features=None,
    max_depth=10,
    random_state=RANDOM_STATE,
    n_jobs=-1
)

print("Randomized Random Forest Classifier...")
randomized_forest_classifier.fit(X_train, y_train)

Randomized Random Forest Classifier...

RandomForestClassifier(max_depth=10, max_features=None, min_samples_leaf=3,
                       min_samples_split=5, n_estimators=200, n_jobs=-1,
                       random_state=777)

In [129]:
y_pred = randomized_forest_classifier.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9

In [130]:
importances = randomized_forest_classifier.feature_importances_
feature_importance = pd.Series(importances, index=X_train.columns)
feature_importance = feature_importance.sort_values(ascending=False)

print(feature_importance)

ram              0.663071
battery_power    0.128776
px_height        0.080423
px_width         0.077016
mobile_wt        0.010806
int_memory       0.006256
m_dep            0.004510
sc_w             0.004060
talk_time        0.004058
n_cores          0.004014
pc               0.003831
clock_speed      0.003578
sc_h             0.003517
fc               0.002763
dual_sim         0.000844
three_g          0.000588
wifi             0.000560
blue             0.000473
four_g           0.000451
touch_screen     0.000404
dtype: float64

In [141]:
important_features = feature_importance[feature_importance > 0.0045].index # Now it is only 7 features

X_train_selected = X_train[important_features]
X_test_selected  = X_test[important_features]

randomized_forest_classifier = RandomForestClassifier(
    n_estimators=200,
    min_samples_split=5,
    min_samples_leaf=3,
    max_features=None,
    max_depth=10,
    random_state=RANDOM_STATE,
    n_jobs=-1
)

print("Randomized Random Forest Classifier...")
randomized_forest_classifier.fit(X_train, y_train)

y_pred = randomized_forest_classifier.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Randomized Random Forest Classifier...
Accuracy: 0.9

In [142]:
add_to_records_table(
    records_table=records_table,
    model_name="Optimized Randomized Random Forest Classifier",
    model_accuracy=accuracy
)

In [143]:
records_table

                                      model_name  model_accuracy
0                       Random Forest Classifier           0.905
1  Optimized Randomized Random Forest Classifier           0.905