In [307]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler, LabelEncoder

from sklearn.model_selection import train_test_split  
from sklearn.model_selection import (
    StratifiedKFold, 
    cross_val_score, 
    cross_validate
)
from sklearn.model_selection import RandomizedSearchCV

from sklearn.linear_model import LogisticRegression  
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier


from sklearn.metrics import accuracy_score

In [308]:
RANDOM_STATE = 777

In [309]:
df = pd.read_csv(
    filepath_or_buffer="gaming_and_mental_health.csv"
)

In [310]:
df.head()

,record_id,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,...,continued_despite_problems,eye_strain,back_neck_pain,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming,gaming_addiction_risk_level
0,GD0001,17,Male,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,...,True,True,False,6.8,3.7,7,1.3,383.70,3,Severe
1,GD0002,21,Male,3.0,MOBA,Dota 2,PC,7.2,Fair,Rarely,...,False,False,False,0.4,8.5,2,10.7,46.64,1,Low
2,GD0003,23,Male,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,...,True,False,True,1.8,7.1,5,3.2,100.81,6,Severe
3,GD0004,20,Female,7.2,RPG,Skyrim,Multi-platform,5.1,Fair,Often,...,False,True,True,0.2,5.2,4,9.1,51.60,7,High
4,GD0005,18,Male,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,...,False,False,False,0.5,6.1,4,4.5,32.57,1,Moderate

In [311]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   record_id                         1000 non-null   object
 1   age                               1000 non-null   int64
 2   gender                            1000 non-null   object
 3   daily_gaming_hours                1000 non-null   float64
 4   game_genre                        1000 non-null   object
 5   primary_game                      1000 non-null   object
 6   gaming_platform                   1000 non-null   object
 7   sleep_hours                       1000 non-null   float64
 8   sleep_quality                     1000 non-null   object
 9   sleep_disruption_frequency        1000 non-null   object
 10  academic_work_performance         1000 non-null   object
 11  grades_gpa                        754 non-null    float64
 12  work_productivity_score           674 non-null    float64
 13  mood_state                        1000 non-null   object
 14  mood_swing_frequency              1000 non-null   object
 15  withdrawal_symptoms               1000 non-null   bool
 16  loss_of_other_interests           1000 non-null   bool
 17  continued_despite_problems        1000 non-null   bool
 18  eye_strain                        1000 non-null   bool
 19  back_neck_pain                    1000 non-null   bool
 20  weight_change_kg                  1000 non-null   float64
 21  exercise_hours_weekly             1000 non-null   float64
 22  social_isolation_score            1000 non-null   int64
 23  face_to_face_social_hours_weekly  1000 non-null   float64
 24  monthly_game_spending_usd         1000 non-null   float64
 25  years_gaming                      1000 non-null   int64
 26  gaming_addiction_risk_level       1000 non-null   object
dtypes: bool(5), float64(8), int64(3), object(11)
memory usage: 176.9+ KB

### Data Preparation

In [312]:
df["gaming_addiction_risk_level"].unique()

array(['Severe', 'Low', 'High', 'Moderate'], dtype=object)

In [313]:
df["record_id"].nunique()

1000

In [314]:
df = df.drop(columns=["record_id"])

In [315]:
columns_to_hot_encode = [
    "gender",
    "game_genre", 
    "primary_game", 
    "gaming_platform",
    "mood_state",
]

df = pd.get_dummies(data=df, columns=columns_to_hot_encode)

In [316]:
sleep_quality_map = {
    "Insomnia": 0,
    "Very Poor": 1,
    "Poor": 2,
    "Fair": 3,
    "Good": 4
}

df["sleep_quality"] = df["sleep_quality"].map(arg=sleep_quality_map)

In [317]:
df["mood_swing_frequency"].unique()

array(['Never', 'Often', 'Rarely', 'Daily', 'Sometimes'], dtype=object)

In [318]:
mood_swing_freq_map = {
    "Never": 0,
    "Rarely": 1,
    "Sometimes": 2,
    "Often": 3,
    "Daily": 4
}

df["mood_swing_frequency"] = df["mood_swing_frequency"].map(mood_swing_freq_map)

In [319]:
academic_perf_map = {
    "Failing": 0,
    "Poor": 1,
    "Below Average": 2,
    "Average": 3,
    "Good": 4,
    "Excellent": 5
}

df["academic_work_performance"] = df["academic_work_performance"].map(academic_perf_map)

In [320]:
df["sleep_disruption_frequency"].unique()

array(['Sometimes', 'Rarely', 'Often', 'Never', 'Always'], dtype=object)

In [321]:
sleep_disruption_map = {
    "Never": 0,
    "Rarely": 1,
    "Sometimes": 2,
    "Often": 3,
    "Always": 4
}

df["sleep_disruption_frequency"] = df["sleep_disruption_frequency"].map(sleep_disruption_map)

In [322]:
boolean_columns = df.select_dtypes(include="bool").columns
df[boolean_columns] = df[boolean_columns].astype(int)

In [323]:
addiction_map = {
    "Low": 0,
    "Moderate": 1,
    "High": 2,
    "Severe": 3
}

df["gaming_addiction_risk_level"] = df["gaming_addiction_risk_level"].map(addiction_map)

In [324]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 68 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   age                                1000 non-null   int64
 1   daily_gaming_hours                 1000 non-null   float64
 2   sleep_hours                        1000 non-null   float64
 3   sleep_quality                      1000 non-null   int64
 4   sleep_disruption_frequency         1000 non-null   int64
 5   academic_work_performance          1000 non-null   int64
 6   grades_gpa                         754 non-null    float64
 7   work_productivity_score            674 non-null    float64
 8   mood_swing_frequency               1000 non-null   int64
 9   withdrawal_symptoms                1000 non-null   int64
 10  loss_of_other_interests            1000 non-null   int64
 11  continued_despite_problems         1000 non-null   int64
 12  eye_strain                         1000 non-null   int64
 13  back_neck_pain                     1000 non-null   int64
 14  weight_change_kg                   1000 non-null   float64
 15  exercise_hours_weekly              1000 non-null   float64
 16  social_isolation_score             1000 non-null   int64
 17  face_to_face_social_hours_weekly   1000 non-null   float64
 18  monthly_game_spending_usd          1000 non-null   float64
 19  years_gaming                       1000 non-null   int64
 20  gaming_addiction_risk_level        1000 non-null   int64
 21  gender_Female                      1000 non-null   int64
 22  gender_Male                        1000 non-null   int64
 23  gender_Other                       1000 non-null   int64
 24  game_genre_Battle Royale           1000 non-null   int64
 25  game_genre_FPS                     1000 non-null   int64
 26  game_genre_MMO                     1000 non-null   int64
 27  game_genre_MOBA                    1000 non-null   int64
 28  game_genre_Mobile Games            1000 non-null   int64
 29  game_genre_RPG                     1000 non-null   int64
 30  game_genre_Strategy                1000 non-null   int64
 31  primary_game_Age of Empires        1000 non-null   int64
 32  primary_game_Apex Legends          1000 non-null   int64
 33  primary_game_CS:GO                 1000 non-null   int64
 34  primary_game_Call of Duty          1000 non-null   int64
 35  primary_game_Candy Crush           1000 non-null   int64
 36  primary_game_Civilization VI       1000 non-null   int64
 37  primary_game_Clash of Clans        1000 non-null   int64
 38  primary_game_Cyberpunk 2077        1000 non-null   int64
 39  primary_game_Dota 2                1000 non-null   int64
 40  primary_game_Elden Ring            1000 non-null   int64
 41  primary_game_Elder Scrolls Online  1000 non-null   int64
 42  primary_game_Final Fantasy XIV     1000 non-null   int64
 43  primary_game_Fortnite              1000 non-null   int64
 44  primary_game_Genshin Impact        1000 non-null   int64
 45  primary_game_League of Legends     1000 non-null   int64
 46  primary_game_Mobile Legends        1000 non-null   int64
 47  primary_game_Overwatch             1000 non-null   int64
 48  primary_game_PUBG                  1000 non-null   int64
 49  primary_game_PUBG Mobile           1000 non-null   int64
 50  primary_game_Skyrim                1000 non-null   int64
 51  primary_game_StarCraft II          1000 non-null   int64
 52  primary_game_Valorant              1000 non-null   int64
 53  primary_game_Warzone               1000 non-null   int64
 54  primary_game_World of Warcraft     1000 non-null   int64
 55  gaming_platform_Console            1000 non-null   int64
 56  gaming_platform_Mobile             1000 non-null   int64
 57  gaming_platform_Multi-platform     1000 non-null   int64
 58  gaming_platform_PC                 1000 non-null   int64
 59  mood_state_Angry                   1000 non-null   int64
 60  mood_state_Anxious                 1000 non-null   int64
 61  mood_state_Depressed               1000 non-null   int64
 62  mood_state_Euphoric                1000 non-null   int64
 63  mood_state_Excited                 1000 non-null   int64
 64  mood_state_Irritable               1000 non-null   int64
 65  mood_state_Normal                  1000 non-null   int64
 66  mood_state_Restless                1000 non-null   int64
 67  mood_state_Withdrawn               1000 non-null   int64
dtypes: float64(8), int64(60)
memory usage: 531.4 KB

#### Handling NULL Values

In [325]:
# NOTE: TEMPORARY
df["grades_gpa"] = df["grades_gpa"].fillna(df["grades_gpa"].median())
df["work_productivity_score"] = (
    df["work_productivity_score"]
    .fillna(df["work_productivity_score"].median())
)

#### Splitting and Scaling

In [326]:
y = df["gaming_addiction_risk_level"]
X = df.drop(columns=["gaming_addiction_risk_level"])

X_train, X_test, y_train, y_test = train_test_split(  
	X, y, test_size=0.2, random_state=RANDOM_STATE  
)

In [327]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### Logistic Regression

#### Simple Logistic Regression

In [328]:
logistic_regression = LogisticRegression(
    C=0.7,
    solver="lbfgs",
    max_iter=5000,
    l1_ratio=0
)

logistic_regression.fit(X_train_scaled, y_train)

LogisticRegression(C=0.7, l1_ratio=0, max_iter=5000)

In [329]:
y_pred = logistic_regression.predict(X_test_scaled)

# Evaluation  
logistic_regression_accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", logistic_regression_accuracy)

Accuracy: 0.92

In [330]:
coefficients = logistic_regression.coef_[0]
odds_ratios = np.exp(coefficients)

feature_importance = pd.DataFrame({
    'feature': X.columns,
    'coefficient': coefficients,
    'odds_ratio': odds_ratios
})

feature_importance.sort_values(by='coefficient', ascending=False)

                             feature  coefficient  odds_ratio
17  face_to_face_social_hours_weekly     0.840375    2.317236
2                        sleep_hours     0.690322    1.994357
15             exercise_hours_weekly     0.409861    1.506608
3                      sleep_quality     0.208737    1.232121
48          primary_game_PUBG Mobile     0.180558    1.197886
..                               ...          ...         ...
18         monthly_game_spending_usd    -1.209464    0.298357
1                 daily_gaming_hours    -1.419983    0.241718
11        continued_despite_problems    -1.584647    0.205020
9                withdrawal_symptoms    -3.024024    0.048605
10           loss_of_other_interests    -3.727873    0.024044

[67 rows x 3 columns]

In [331]:
treshold = 0.2

feature_importance = feature_importance[abs(feature_importance["coefficient"]) > treshold]

feature_importance.sort_values(by='coefficient', ascending=False)
important_columns = feature_importance["feature"]

In [332]:
y = df["gaming_addiction_risk_level"]
X = df.drop(columns=["gaming_addiction_risk_level"])

X = X.loc[:, important_columns]

X_train, X_test, y_train, y_test = train_test_split(  
	X, y, test_size=0.2, random_state=RANDOM_STATE  
) 

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [333]:
logistic_regression = LogisticRegression(
    C=0.7,
    solver="lbfgs",
    max_iter=5000,
    l1_ratio=0
)

logistic_regression.fit(X_train_scaled, y_train)

y_pred = logistic_regression.predict(X_test_scaled)

# Evaluation  
logistic_regression_accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", logistic_regression_accuracy)

Accuracy: 0.97

#### Cross Validation with Logistic Regression

In [334]:
y = df["gaming_addiction_risk_level"]
X = df.drop(columns=["gaming_addiction_risk_level"])

X_train, X_test, y_train, y_test = train_test_split(  
	X, y, test_size=0.2, random_state=RANDOM_STATE  
) 

X_scaled = scaler.fit_transform(X)
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [335]:
scoring = ["accuracy", "f1_weighted", "precision_weighted", "recall_weighted"]

logistic_regression = LogisticRegression(
    C=0.7,
    solver="lbfgs",
    max_iter=5000,
    l1_ratio=0
)

cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=RANDOM_STATE)
scores = cross_val_score(logistic_regression, X_scaled, y, cv=cv, scoring="f1_weighted")

print("Fold accuracies:", scores)
print("Mean F1 Weighted:", np.mean(scores))

Fold accuracies: [0.93910714 0.97957521 0.95042184 0.96088204 0.96       0.96054586
 0.95963801 0.98       0.93982906 0.96040504]
Mean F1 Weighted: 0.959040420181547

In [336]:
results = cross_validate(
    logistic_regression,
    X_scaled,
    y,
    cv=cv,
    scoring=scoring
)

for metric in scoring:
    print(metric, results["test_" + metric].mean())

accuracy 0.959
f1_weighted 0.959040420181547
precision_weighted 0.9610947447805032
recall_weighted 0.959

#### Random Search of Hyperparameters

In [337]:
y = df["gaming_addiction_risk_level"]
X = df.drop(columns=["gaming_addiction_risk_level"])

X_train, X_test, y_train, y_test = train_test_split(  
	X, y, test_size=0.2, random_state=RANDOM_STATE  
) 

X_scaled = scaler.fit_transform(X)
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [338]:
param_grid = {
    "C": np.linspace(start=0.001, stop=1, num=30),
    "solver": ['lbfgs', 'newton-cg', 'newton-cholesky', 'sag', 'saga'],
    "max_iter": [num for num in range(100, 5000, 250)]
}

rn_logistic_regression = RandomizedSearchCV(
    estimator=LogisticRegression(),
    param_distributions=param_grid,
    n_iter=20,
    cv=5,
    scoring="accuracy",
    random_state=RANDOM_STATE,
    n_jobs=-1
)


rn_logistic_regression.fit(X_train_scaled, y_train)

print("Best Parameters:", rn_logistic_regression.best_params_)
print("Best CV Score:", rn_logistic_regression.best_score_)

Best Parameters: {'solver': 'sag', 'max_iter': 3100, 'C': np.float64(0.965551724137931)}
Best CV Score: 0.9325000000000001

In [339]:
scoring = ["accuracy", "f1_weighted", "precision_weighted", "recall_weighted"]

rn_logistic_regression = rn_logistic_regression.best_estimator_
results = cross_validate(
    rn_logistic_regression,
    X_scaled,
    y,
    cv=cv,
    scoring=scoring
)

for metric in scoring:
    print(metric, results["test_" + metric].mean())

accuracy 0.9599999999999997
f1_weighted 0.9600766301453154
precision_weighted 0.9621152926150216
recall_weighted 0.9599999999999997

In [340]:
importances = np.abs(rn_logistic_regression.coef_[0])
feature_importance = pd.Series(importances, index=X_train.columns)
feature_importance = feature_importance.sort_values(ascending=False)  
print(feature_importance)

important_features = feature_importance[feature_importance > 0.5].index
X_train_selected = X_train[important_features]
X_test_selected = X_test[important_features]

important_features

loss_of_other_interests           4.081475
withdrawal_symptoms               3.366318
continued_despite_problems        1.789975
daily_gaming_hours                1.572587
monthly_game_spending_usd         1.350181
                                    ...
primary_game_CS:GO                0.009523
mood_state_Anxious                0.009314
mood_state_Irritable              0.008702
gaming_platform_Multi-platform    0.004675
mood_state_Normal                 0.003132
Length: 67, dtype: float64

Index(['loss_of_other_interests', 'withdrawal_symptoms',
       'continued_despite_problems', 'daily_gaming_hours',
       'monthly_game_spending_usd', 'social_isolation_score',
       'face_to_face_social_hours_weekly', 'sleep_hours'],
      dtype='object')

In [341]:
X_train_scaled = scaler.fit_transform(X_train_selected)
X_test_scaled = scaler.transform(X_test_selected)       

logistic_regression = LogisticRegression(
    C=np.float64(0.965551724137931),
    max_iter=3100,
    solver='sag'
)

logistic_regression.fit(X_train_scaled, y_train)

LogisticRegression(C=np.float64(0.965551724137931), max_iter=3100, solver='sag')

In [342]:
results = cross_validate(
    rn_logistic_regression,
    X_scaled,
    y,
    cv=cv,
    scoring=scoring
)

for metric in scoring:
    print(metric, results["test_" + metric].mean())

accuracy 0.9599999999999997
f1_weighted 0.9600766301453154
precision_weighted 0.9621152926150216
recall_weighted 0.9599999999999997

### KNeighbors Classifier

In [343]:
y = df["gaming_addiction_risk_level"]
X = df.drop(columns=["gaming_addiction_risk_level"])

X_train, X_test, y_train, y_test = train_test_split(  
	X, y, test_size=0.2, random_state=RANDOM_STATE  
) 

X_scaled = scaler.fit_transform(X)
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [344]:
knn = KNeighborsClassifier(
    n_neighbors=5,
    weights="distance",
    metric="minkowski",
    p=2
)
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier(weights='distance')

In [345]:
results = cross_validate(
    knn,
    X_scaled,
    y,
    cv=cv,
    scoring=scoring
)

for metric in scoring:
    print(metric, results["test_" + metric].mean())

accuracy 0.688
f1_weighted 0.6570794736998234
precision_weighted 0.6564072872908041
recall_weighted 0.688

#### Random Search of Hyperparameters for KNN

In [346]:
param_grid = {
    "n_neighbors": list(range(3, 25)),
    "weights": ["uniform", "distance"],
    "p": [1, 2],
    "algorithm": ['auto', 'ball_tree', 'kd_tree', 'brute']
}

random_knn = RandomizedSearchCV(
    estimator=KNeighborsClassifier(),
    param_distributions=param_grid,
    n_iter=20, # number of random combinations
    cv=5,
    scoring="accuracy",
    random_state=RANDOM_STATE,
    n_jobs=-1
)

random_knn.fit(X_train_scaled, y_train)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(), n_iter=20, n_jobs=-1,
                   param_distributions={'algorithm': ['auto', 'ball_tree',
                                                      'kd_tree', 'brute'],
                                        'n_neighbors': [3, 4, 5, 6, 7, 8, 9, 10,
                                                        11, 12, 13, 14, 15, 16,
                                                        17, 18, 19, 20, 21, 22,
                                                        23, 24],
                                        'p': [1, 2],
                                        'weights': ['uniform', 'distance']},
                   random_state=777, scoring='accuracy')

In [347]:
print("Best Parameters (Random):", random_knn.best_params_)

best_knn = random_knn.best_estimator_

Best Parameters (Random): {'weights': 'distance', 'p': 1, 'n_neighbors': 4, 'algorithm': 'brute'}

In [348]:
results = cross_validate(
    random_knn,
    X_scaled,
    y,
    cv=cv,
    scoring=scoring
)

for metric in scoring:
    print(metric, results["test_" + metric].mean())

accuracy 0.694
f1_weighted 0.6650430220524461
precision_weighted 0.6619742817675591
recall_weighted 0.694

### Boosting Techniques

#### Gradient Boosting Classifier

In [349]:
y = df["gaming_addiction_risk_level"]
X = df.drop(columns=["gaming_addiction_risk_level"])

X_train, X_test, y_train, y_test = train_test_split(  
	X, y, test_size=0.2, random_state=RANDOM_STATE  
)

In [350]:
gradient_boosting = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    subsample=0.8,
    random_state=42
)

gradient_boosting.fit(X_train, y_train)

GradientBoostingClassifier(learning_rate=0.05, n_estimators=200,
                           random_state=42, subsample=0.8)

In [351]:
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=RANDOM_STATE)

In [352]:
results = cross_validate(
    gradient_boosting,
    X,
    y,
    cv=cv,
    scoring=scoring
)

for metric in scoring:
    print(metric, results["test_" + metric].mean())

accuracy 0.961
f1_weighted 0.9609063976956674
precision_weighted 0.964005013368984
recall_weighted 0.961

#### Extreme Gradient Boosting

In [353]:
extreme_gb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.1,
    reg_lambda=1.0,
    random_state=42,
    use_label_encoder=False,
    eval_metric="logloss"
)

extreme_gb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

In [354]:
results = cross_validate(
    extreme_gb,
    X,
    y,
    cv=cv,
    scoring=scoring
)

for metric in scoring:
    print(metric, results["test_" + metric].mean())

accuracy 0.9760000000000002
f1_weighted 0.9760396117341807
precision_weighted 0.9773603641456583
recall_weighted 0.9760000000000002

### Cat Boosting

In [355]:
cat_boosting = CatBoostClassifier(
    iterations=300,
    learning_rate=0.05,
    depth=6,
    l2_leaf_reg=3.0,
    random_state=42,
    verbose=False
)

cat_boosting.fit(X_train, y_train)

In [356]:
y_pred = cat_boosting.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 1.0