In [35]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler, LabelEncoder

In [36]:
df = pd.read_csv(
    filepath_or_buffer="gaming_and_mental_health.csv"
)

In [37]:
df.head()

,record_id,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,...,continued_despite_problems,eye_strain,back_neck_pain,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming,gaming_addiction_risk_level
0,GD0001,17,Male,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,...,True,True,False,6.8,3.7,7,1.3,383.70,3,Severe
1,GD0002,21,Male,3.0,MOBA,Dota 2,PC,7.2,Fair,Rarely,...,False,False,False,0.4,8.5,2,10.7,46.64,1,Low
2,GD0003,23,Male,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,...,True,False,True,1.8,7.1,5,3.2,100.81,6,Severe
3,GD0004,20,Female,7.2,RPG,Skyrim,Multi-platform,5.1,Fair,Often,...,False,True,True,0.2,5.2,4,9.1,51.60,7,High
4,GD0005,18,Male,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,...,False,False,False,0.5,6.1,4,4.5,32.57,1,Moderate

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   record_id                         1000 non-null   object
 1   age                               1000 non-null   int64
 2   gender                            1000 non-null   object
 3   daily_gaming_hours                1000 non-null   float64
 4   game_genre                        1000 non-null   object
 5   primary_game                      1000 non-null   object
 6   gaming_platform                   1000 non-null   object
 7   sleep_hours                       1000 non-null   float64
 8   sleep_quality                     1000 non-null   object
 9   sleep_disruption_frequency        1000 non-null   object
 10  academic_work_performance         1000 non-null   object
 11  grades_gpa                        754 non-null    float64
 12  work_productivity_score           674 non-null    float64
 13  mood_state                        1000 non-null   object
 14  mood_swing_frequency              1000 non-null   object
 15  withdrawal_symptoms               1000 non-null   bool
 16  loss_of_other_interests           1000 non-null   bool
 17  continued_despite_problems        1000 non-null   bool
 18  eye_strain                        1000 non-null   bool
 19  back_neck_pain                    1000 non-null   bool
 20  weight_change_kg                  1000 non-null   float64
 21  exercise_hours_weekly             1000 non-null   float64
 22  social_isolation_score            1000 non-null   int64
 23  face_to_face_social_hours_weekly  1000 non-null   float64
 24  monthly_game_spending_usd         1000 non-null   float64
 25  years_gaming                      1000 non-null   int64
 26  gaming_addiction_risk_level       1000 non-null   object
dtypes: bool(5), float64(8), int64(3), object(11)
memory usage: 176.9+ KB

### Data Preparation

In [39]:
df["gaming_addiction_risk_level"].unique()

array(['Severe', 'Low', 'High', 'Moderate'], dtype=object)

In [40]:
df["record_id"].nunique()

1000

In [41]:
df = df.drop(columns=["record_id"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   age                               1000 non-null   int64
 1   gender                            1000 non-null   object
 2   daily_gaming_hours                1000 non-null   float64
 3   game_genre                        1000 non-null   object
 4   primary_game                      1000 non-null   object
 5   gaming_platform                   1000 non-null   object
 6   sleep_hours                       1000 non-null   float64
 7   sleep_quality                     1000 non-null   object
 8   sleep_disruption_frequency        1000 non-null   object
 9   academic_work_performance         1000 non-null   object
 10  grades_gpa                        754 non-null    float64
 11  work_productivity_score           674 non-null    float64
 12  mood_state                        1000 non-null   object
 13  mood_swing_frequency              1000 non-null   object
 14  withdrawal_symptoms               1000 non-null   bool
 15  loss_of_other_interests           1000 non-null   bool
 16  continued_despite_problems        1000 non-null   bool
 17  eye_strain                        1000 non-null   bool
 18  back_neck_pain                    1000 non-null   bool
 19  weight_change_kg                  1000 non-null   float64
 20  exercise_hours_weekly             1000 non-null   float64
 21  social_isolation_score            1000 non-null   int64
 22  face_to_face_social_hours_weekly  1000 non-null   float64
 23  monthly_game_spending_usd         1000 non-null   float64
 24  years_gaming                      1000 non-null   int64
 25  gaming_addiction_risk_level       1000 non-null   object
dtypes: bool(5), float64(8), int64(3), object(10)
memory usage: 169.1+ KB

In [42]:
df["gender"].unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [43]:
df = pd.get_dummies(data=df, columns=["gender"])

In [44]:
df

,age,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,academic_work_performance,grades_gpa,...,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming,gaming_addiction_risk_level,gender_Female,gender_Male,gender_Other
0,17,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,Below Average,1.25,...,6.8,3.7,7,1.3,383.70,3,Severe,False,True,False
1,21,3.0,MOBA,Dota 2,PC,7.2,Fair,Rarely,Good,3.75,...,0.4,8.5,2,10.7,46.64,1,Low,False,True,False
2,23,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,Poor,NaN,...,1.8,7.1,5,3.2,100.81,6,Severe,False,True,False
3,20,7.2,RPG,Skyrim,Multi-platform,5.1,Fair,Often,Poor,1.62,...,0.2,5.2,4,9.1,51.60,7,High,True,False,False
4,18,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,Average,2.44,...,0.5,6.1,4,4.5,32.57,1,Moderate,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,15,8.6,Strategy,Age of Empires,PC,4.1,Very Poor,Always,Average,2.96,...,1.9,7.5,6,2.4,426.54,3,Severe,True,False,False
996,18,5.4,MMO,Elder Scrolls Online,Multi-platform,6.5,Fair,Never,Excellent,3.42,...,2.1,7.7,1,10.9,83.71,7,Low,False,True,False
997,23,7.3,RPG,Skyrim,PC,3.9,Insomnia,Rarely,Poor,NaN,...,0.5,8.1,5,6.7,88.60,5,High,False,True,False
998,18,3.1,Strategy,StarCraft II,Console,8.2,Fair,Sometimes,Good,1.03,...,0.8,8.4,1,12.7,22.02,8,Low,False,True,False
999,29,3.5,RPG,Cyberpunk 2077,Multi-platform,7.4,Good,Sometimes,Below Average,NaN,...,0.0,9.3,2,10.9,25.20,19,Low,False,True,False