In [99]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler, LabelEncoder

In [100]:
df = pd.read_csv(
    filepath_or_buffer="gaming_and_mental_health.csv"
)

In [101]:
df.head()

,record_id,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,...,continued_despite_problems,eye_strain,back_neck_pain,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming,gaming_addiction_risk_level
0,GD0001,17,Male,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,...,True,True,False,6.8,3.7,7,1.3,383.70,3,Severe
1,GD0002,21,Male,3.0,MOBA,Dota 2,PC,7.2,Fair,Rarely,...,False,False,False,0.4,8.5,2,10.7,46.64,1,Low
2,GD0003,23,Male,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,...,True,False,True,1.8,7.1,5,3.2,100.81,6,Severe
3,GD0004,20,Female,7.2,RPG,Skyrim,Multi-platform,5.1,Fair,Often,...,False,True,True,0.2,5.2,4,9.1,51.60,7,High
4,GD0005,18,Male,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,...,False,False,False,0.5,6.1,4,4.5,32.57,1,Moderate

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   record_id                         1000 non-null   object
 1   age                               1000 non-null   int64
 2   gender                            1000 non-null   object
 3   daily_gaming_hours                1000 non-null   float64
 4   game_genre                        1000 non-null   object
 5   primary_game                      1000 non-null   object
 6   gaming_platform                   1000 non-null   object
 7   sleep_hours                       1000 non-null   float64
 8   sleep_quality                     1000 non-null   object
 9   sleep_disruption_frequency        1000 non-null   object
 10  academic_work_performance         1000 non-null   object
 11  grades_gpa                        754 non-null    float64
 12  work_productivity_score           674 non-null    float64
 13  mood_state                        1000 non-null   object
 14  mood_swing_frequency              1000 non-null   object
 15  withdrawal_symptoms               1000 non-null   bool
 16  loss_of_other_interests           1000 non-null   bool
 17  continued_despite_problems        1000 non-null   bool
 18  eye_strain                        1000 non-null   bool
 19  back_neck_pain                    1000 non-null   bool
 20  weight_change_kg                  1000 non-null   float64
 21  exercise_hours_weekly             1000 non-null   float64
 22  social_isolation_score            1000 non-null   int64
 23  face_to_face_social_hours_weekly  1000 non-null   float64
 24  monthly_game_spending_usd         1000 non-null   float64
 25  years_gaming                      1000 non-null   int64
 26  gaming_addiction_risk_level       1000 non-null   object
dtypes: bool(5), float64(8), int64(3), object(11)
memory usage: 176.9+ KB

### Data Preparation

In [103]:
df["gaming_addiction_risk_level"].unique()

array(['Severe', 'Low', 'High', 'Moderate'], dtype=object)

In [104]:
df["record_id"].nunique()

1000

In [105]:
df = df.drop(columns=["record_id"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   age                               1000 non-null   int64
 1   gender                            1000 non-null   object
 2   daily_gaming_hours                1000 non-null   float64
 3   game_genre                        1000 non-null   object
 4   primary_game                      1000 non-null   object
 5   gaming_platform                   1000 non-null   object
 6   sleep_hours                       1000 non-null   float64
 7   sleep_quality                     1000 non-null   object
 8   sleep_disruption_frequency        1000 non-null   object
 9   academic_work_performance         1000 non-null   object
 10  grades_gpa                        754 non-null    float64
 11  work_productivity_score           674 non-null    float64
 12  mood_state                        1000 non-null   object
 13  mood_swing_frequency              1000 non-null   object
 14  withdrawal_symptoms               1000 non-null   bool
 15  loss_of_other_interests           1000 non-null   bool
 16  continued_despite_problems        1000 non-null   bool
 17  eye_strain                        1000 non-null   bool
 18  back_neck_pain                    1000 non-null   bool
 19  weight_change_kg                  1000 non-null   float64
 20  exercise_hours_weekly             1000 non-null   float64
 21  social_isolation_score            1000 non-null   int64
 22  face_to_face_social_hours_weekly  1000 non-null   float64
 23  monthly_game_spending_usd         1000 non-null   float64
 24  years_gaming                      1000 non-null   int64
 25  gaming_addiction_risk_level       1000 non-null   object
dtypes: bool(5), float64(8), int64(3), object(10)
memory usage: 169.1+ KB

In [106]:
df["gender"].unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [107]:
df = pd.get_dummies(data=df, columns=["gender"])

In [108]:
df

,age,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,academic_work_performance,grades_gpa,...,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming,gaming_addiction_risk_level,gender_Female,gender_Male,gender_Other
0,17,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,Below Average,1.25,...,6.8,3.7,7,1.3,383.70,3,Severe,False,True,False
1,21,3.0,MOBA,Dota 2,PC,7.2,Fair,Rarely,Good,3.75,...,0.4,8.5,2,10.7,46.64,1,Low,False,True,False
2,23,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,Poor,NaN,...,1.8,7.1,5,3.2,100.81,6,Severe,False,True,False
3,20,7.2,RPG,Skyrim,Multi-platform,5.1,Fair,Often,Poor,1.62,...,0.2,5.2,4,9.1,51.60,7,High,True,False,False
4,18,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,Average,2.44,...,0.5,6.1,4,4.5,32.57,1,Moderate,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,15,8.6,Strategy,Age of Empires,PC,4.1,Very Poor,Always,Average,2.96,...,1.9,7.5,6,2.4,426.54,3,Severe,True,False,False
996,18,5.4,MMO,Elder Scrolls Online,Multi-platform,6.5,Fair,Never,Excellent,3.42,...,2.1,7.7,1,10.9,83.71,7,Low,False,True,False
997,23,7.3,RPG,Skyrim,PC,3.9,Insomnia,Rarely,Poor,NaN,...,0.5,8.1,5,6.7,88.60,5,High,False,True,False
998,18,3.1,Strategy,StarCraft II,Console,8.2,Fair,Sometimes,Good,1.03,...,0.8,8.4,1,12.7,22.02,8,Low,False,True,False
999,29,3.5,RPG,Cyberpunk 2077,Multi-platform,7.4,Good,Sometimes,Below Average,NaN,...,0.0,9.3,2,10.9,25.20,19,Low,False,True,False

In [109]:
df = pd.get_dummies(data=df, columns=["game_genre", "primary_game", "gaming_platform"])

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 60 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   age                                1000 non-null   int64
 1   daily_gaming_hours                 1000 non-null   float64
 2   sleep_hours                        1000 non-null   float64
 3   sleep_quality                      1000 non-null   object
 4   sleep_disruption_frequency         1000 non-null   object
 5   academic_work_performance          1000 non-null   object
 6   grades_gpa                         754 non-null    float64
 7   work_productivity_score            674 non-null    float64
 8   mood_state                         1000 non-null   object
 9   mood_swing_frequency               1000 non-null   object
 10  withdrawal_symptoms                1000 non-null   bool
 11  loss_of_other_interests            1000 non-null   bool
 12  continued_despite_problems         1000 non-null   bool
 13  eye_strain                         1000 non-null   bool
 14  back_neck_pain                     1000 non-null   bool
 15  weight_change_kg                   1000 non-null   float64
 16  exercise_hours_weekly              1000 non-null   float64
 17  social_isolation_score             1000 non-null   int64
 18  face_to_face_social_hours_weekly   1000 non-null   float64
 19  monthly_game_spending_usd          1000 non-null   float64
 20  years_gaming                       1000 non-null   int64
 21  gaming_addiction_risk_level        1000 non-null   object
 22  gender_Female                      1000 non-null   bool
 23  gender_Male                        1000 non-null   bool
 24  gender_Other                       1000 non-null   bool
 25  game_genre_Battle Royale           1000 non-null   bool
 26  game_genre_FPS                     1000 non-null   bool
 27  game_genre_MMO                     1000 non-null   bool
 28  game_genre_MOBA                    1000 non-null   bool
 29  game_genre_Mobile Games            1000 non-null   bool
 30  game_genre_RPG                     1000 non-null   bool
 31  game_genre_Strategy                1000 non-null   bool
 32  primary_game_Age of Empires        1000 non-null   bool
 33  primary_game_Apex Legends          1000 non-null   bool
 34  primary_game_CS:GO                 1000 non-null   bool
 35  primary_game_Call of Duty          1000 non-null   bool
 36  primary_game_Candy Crush           1000 non-null   bool
 37  primary_game_Civilization VI       1000 non-null   bool
 38  primary_game_Clash of Clans        1000 non-null   bool
 39  primary_game_Cyberpunk 2077        1000 non-null   bool
 40  primary_game_Dota 2                1000 non-null   bool
 41  primary_game_Elden Ring            1000 non-null   bool
 42  primary_game_Elder Scrolls Online  1000 non-null   bool
 43  primary_game_Final Fantasy XIV     1000 non-null   bool
 44  primary_game_Fortnite              1000 non-null   bool
 45  primary_game_Genshin Impact        1000 non-null   bool
 46  primary_game_League of Legends     1000 non-null   bool
 47  primary_game_Mobile Legends        1000 non-null   bool
 48  primary_game_Overwatch             1000 non-null   bool
 49  primary_game_PUBG                  1000 non-null   bool
 50  primary_game_PUBG Mobile           1000 non-null   bool
 51  primary_game_Skyrim                1000 non-null   bool
 52  primary_game_StarCraft II          1000 non-null   bool
 53  primary_game_Valorant              1000 non-null   bool
 54  primary_game_Warzone               1000 non-null   bool
 55  primary_game_World of Warcraft     1000 non-null   bool
 56  gaming_platform_Console            1000 non-null   bool
 57  gaming_platform_Mobile             1000 non-null   bool
 58  gaming_platform_Multi-platform     1000 non-null   bool
 59  gaming_platform_PC                 1000 non-null   bool
dtypes: bool(43), float64(8), int64(3), object(6)
memory usage: 174.9+ KB

In [111]:
df.head()

,age,daily_gaming_hours,sleep_hours,sleep_quality,sleep_disruption_frequency,academic_work_performance,grades_gpa,work_productivity_score,mood_state,mood_swing_frequency,...,primary_game_PUBG Mobile,primary_game_Skyrim,primary_game_StarCraft II,primary_game_Valorant,primary_game_Warzone,primary_game_World of Warcraft,gaming_platform_Console,gaming_platform_Mobile,gaming_platform_Multi-platform,gaming_platform_PC
0,17,11.1,3.7,Very Poor,Sometimes,Below Average,1.25,NaN,Anxious,Never,...,False,False,False,False,False,False,False,False,False,True
1,21,3.0,7.2,Fair,Rarely,Good,3.75,2.0,Irritable,Often,...,False,False,False,False,False,False,False,False,False,True
2,23,7.6,4.4,Fair,Often,Poor,NaN,9.0,Irritable,Rarely,...,False,False,False,False,False,False,False,False,True,False
3,20,7.2,5.1,Fair,Often,Poor,1.62,2.0,Withdrawn,Daily,...,False,True,False,False,False,False,False,False,True,False
4,18,6.8,3.4,Poor,Never,Average,2.44,NaN,Angry,Daily,...,False,False,False,False,False,False,False,False,False,True

In [112]:
sleep_quality_map = {
    "Insomnia": 0,
    "Very Poor": 1,
    "Poor": 2,
    "Fair": 3,
    "Good": 4
}

df["sleep_quality"] = df["sleep_quality"].map(arg=sleep_quality_map)

In [113]:
mood_swing_freq_map = {
    "Never": 0,
    "Rarely": 1,
    "Sometimes": 2,
    "Often": 3,
    "Always": 4
}

df["mood_swing_frequency"] = df["mood_swing_frequency"].map(mood_swing_freq_map)

In [114]:
academic_perf_map = {
    "Failing": 0,
    "Poor": 1,
    "Below Average": 2,
    "Average": 3,
    "Good": 4,
    "Excellent": 5
}

df["academic_work_performance"] = df["academic_work_performance"].map(academic_perf_map)

In [115]:
df = pd.get_dummies(df, columns=["mood_state"], drop_first=True)

In [116]:
sleep_disruption_map = {
    "Never": 0,
    "Rarely": 1,
    "Sometimes": 2,
    "Often": 3,
    "Daily": 4
}

df["sleep_disruption_frequency"] = df["sleep_disruption_frequency"].map(sleep_disruption_map)

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 67 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   age                                1000 non-null   int64
 1   daily_gaming_hours                 1000 non-null   float64
 2   sleep_hours                        1000 non-null   float64
 3   sleep_quality                      1000 non-null   int64
 4   sleep_disruption_frequency         819 non-null    float64
 5   academic_work_performance          1000 non-null   int64
 6   grades_gpa                         754 non-null    float64
 7   work_productivity_score            674 non-null    float64
 8   mood_swing_frequency               794 non-null    float64
 9   withdrawal_symptoms                1000 non-null   bool
 10  loss_of_other_interests            1000 non-null   bool
 11  continued_despite_problems         1000 non-null   bool
 12  eye_strain                         1000 non-null   bool
 13  back_neck_pain                     1000 non-null   bool
 14  weight_change_kg                   1000 non-null   float64
 15  exercise_hours_weekly              1000 non-null   float64
 16  social_isolation_score             1000 non-null   int64
 17  face_to_face_social_hours_weekly   1000 non-null   float64
 18  monthly_game_spending_usd          1000 non-null   float64
 19  years_gaming                       1000 non-null   int64
 20  gaming_addiction_risk_level        1000 non-null   object
 21  gender_Female                      1000 non-null   bool
 22  gender_Male                        1000 non-null   bool
 23  gender_Other                       1000 non-null   bool
 24  game_genre_Battle Royale           1000 non-null   bool
 25  game_genre_FPS                     1000 non-null   bool
 26  game_genre_MMO                     1000 non-null   bool
 27  game_genre_MOBA                    1000 non-null   bool
 28  game_genre_Mobile Games            1000 non-null   bool
 29  game_genre_RPG                     1000 non-null   bool
 30  game_genre_Strategy                1000 non-null   bool
 31  primary_game_Age of Empires        1000 non-null   bool
 32  primary_game_Apex Legends          1000 non-null   bool
 33  primary_game_CS:GO                 1000 non-null   bool
 34  primary_game_Call of Duty          1000 non-null   bool
 35  primary_game_Candy Crush           1000 non-null   bool
 36  primary_game_Civilization VI       1000 non-null   bool
 37  primary_game_Clash of Clans        1000 non-null   bool
 38  primary_game_Cyberpunk 2077        1000 non-null   bool
 39  primary_game_Dota 2                1000 non-null   bool
 40  primary_game_Elden Ring            1000 non-null   bool
 41  primary_game_Elder Scrolls Online  1000 non-null   bool
 42  primary_game_Final Fantasy XIV     1000 non-null   bool
 43  primary_game_Fortnite              1000 non-null   bool
 44  primary_game_Genshin Impact        1000 non-null   bool
 45  primary_game_League of Legends     1000 non-null   bool
 46  primary_game_Mobile Legends        1000 non-null   bool
 47  primary_game_Overwatch             1000 non-null   bool
 48  primary_game_PUBG                  1000 non-null   bool
 49  primary_game_PUBG Mobile           1000 non-null   bool
 50  primary_game_Skyrim                1000 non-null   bool
 51  primary_game_StarCraft II          1000 non-null   bool
 52  primary_game_Valorant              1000 non-null   bool
 53  primary_game_Warzone               1000 non-null   bool
 54  primary_game_World of Warcraft     1000 non-null   bool
 55  gaming_platform_Console            1000 non-null   bool
 56  gaming_platform_Mobile             1000 non-null   bool
 57  gaming_platform_Multi-platform     1000 non-null   bool
 58  gaming_platform_PC                 1000 non-null   bool
 59  mood_state_Anxious                 1000 non-null   bool
 60  mood_state_Depressed               1000 non-null   bool
 61  mood_state_Euphoric                1000 non-null   bool
 62  mood_state_Excited                 1000 non-null   bool
 63  mood_state_Irritable               1000 non-null   bool
 64  mood_state_Normal                  1000 non-null   bool
 65  mood_state_Restless                1000 non-null   bool
 66  mood_state_Withdrawn               1000 non-null   bool
dtypes: bool(51), float64(10), int64(5), object(1)
memory usage: 174.9+ KB

In [119]:
boolean_columns = df.select_dtypes(include="bool").columns
df[boolean_columns] = df[boolean_columns].astype(int)

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 67 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   age                                1000 non-null   int64
 1   daily_gaming_hours                 1000 non-null   float64
 2   sleep_hours                        1000 non-null   float64
 3   sleep_quality                      1000 non-null   int64
 4   sleep_disruption_frequency         819 non-null    float64
 5   academic_work_performance          1000 non-null   int64
 6   grades_gpa                         754 non-null    float64
 7   work_productivity_score            674 non-null    float64
 8   mood_swing_frequency               794 non-null    float64
 9   withdrawal_symptoms                1000 non-null   int64
 10  loss_of_other_interests            1000 non-null   int64
 11  continued_despite_problems         1000 non-null   int64
 12  eye_strain                         1000 non-null   int64
 13  back_neck_pain                     1000 non-null   int64
 14  weight_change_kg                   1000 non-null   float64
 15  exercise_hours_weekly              1000 non-null   float64
 16  social_isolation_score             1000 non-null   int64
 17  face_to_face_social_hours_weekly   1000 non-null   float64
 18  monthly_game_spending_usd          1000 non-null   float64
 19  years_gaming                       1000 non-null   int64
 20  gaming_addiction_risk_level        1000 non-null   object
 21  gender_Female                      1000 non-null   int64
 22  gender_Male                        1000 non-null   int64
 23  gender_Other                       1000 non-null   int64
 24  game_genre_Battle Royale           1000 non-null   int64
 25  game_genre_FPS                     1000 non-null   int64
 26  game_genre_MMO                     1000 non-null   int64
 27  game_genre_MOBA                    1000 non-null   int64
 28  game_genre_Mobile Games            1000 non-null   int64
 29  game_genre_RPG                     1000 non-null   int64
 30  game_genre_Strategy                1000 non-null   int64
 31  primary_game_Age of Empires        1000 non-null   int64
 32  primary_game_Apex Legends          1000 non-null   int64
 33  primary_game_CS:GO                 1000 non-null   int64
 34  primary_game_Call of Duty          1000 non-null   int64
 35  primary_game_Candy Crush           1000 non-null   int64
 36  primary_game_Civilization VI       1000 non-null   int64
 37  primary_game_Clash of Clans        1000 non-null   int64
 38  primary_game_Cyberpunk 2077        1000 non-null   int64
 39  primary_game_Dota 2                1000 non-null   int64
 40  primary_game_Elden Ring            1000 non-null   int64
 41  primary_game_Elder Scrolls Online  1000 non-null   int64
 42  primary_game_Final Fantasy XIV     1000 non-null   int64
 43  primary_game_Fortnite              1000 non-null   int64
 44  primary_game_Genshin Impact        1000 non-null   int64
 45  primary_game_League of Legends     1000 non-null   int64
 46  primary_game_Mobile Legends        1000 non-null   int64
 47  primary_game_Overwatch             1000 non-null   int64
 48  primary_game_PUBG                  1000 non-null   int64
 49  primary_game_PUBG Mobile           1000 non-null   int64
 50  primary_game_Skyrim                1000 non-null   int64
 51  primary_game_StarCraft II          1000 non-null   int64
 52  primary_game_Valorant              1000 non-null   int64
 53  primary_game_Warzone               1000 non-null   int64
 54  primary_game_World of Warcraft     1000 non-null   int64
 55  gaming_platform_Console            1000 non-null   int64
 56  gaming_platform_Mobile             1000 non-null   int64
 57  gaming_platform_Multi-platform     1000 non-null   int64
 58  gaming_platform_PC                 1000 non-null   int64
 59  mood_state_Anxious                 1000 non-null   int64
 60  mood_state_Depressed               1000 non-null   int64
 61  mood_state_Euphoric                1000 non-null   int64
 62  mood_state_Excited                 1000 non-null   int64
 63  mood_state_Irritable               1000 non-null   int64
 64  mood_state_Normal                  1000 non-null   int64
 65  mood_state_Restless                1000 non-null   int64
 66  mood_state_Withdrawn               1000 non-null   int64
dtypes: float64(10), int64(56), object(1)
memory usage: 523.6+ KB

In [123]:
addiction_map = {
    "Low": 0,
    "Moderate": 1,
    "High": 2,
    "Severe": 3
}

df["gaming_addiction_risk_level"] = df["gaming_addiction_risk_level"].map(addiction_map)

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 67 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   age                                1000 non-null   int64
 1   daily_gaming_hours                 1000 non-null   float64
 2   sleep_hours                        1000 non-null   float64
 3   sleep_quality                      1000 non-null   int64
 4   sleep_disruption_frequency         819 non-null    float64
 5   academic_work_performance          1000 non-null   int64
 6   grades_gpa                         754 non-null    float64
 7   work_productivity_score            674 non-null    float64
 8   mood_swing_frequency               794 non-null    float64
 9   withdrawal_symptoms                1000 non-null   int64
 10  loss_of_other_interests            1000 non-null   int64
 11  continued_despite_problems         1000 non-null   int64
 12  eye_strain                         1000 non-null   int64
 13  back_neck_pain                     1000 non-null   int64
 14  weight_change_kg                   1000 non-null   float64
 15  exercise_hours_weekly              1000 non-null   float64
 16  social_isolation_score             1000 non-null   int64
 17  face_to_face_social_hours_weekly   1000 non-null   float64
 18  monthly_game_spending_usd          1000 non-null   float64
 19  years_gaming                       1000 non-null   int64
 20  gaming_addiction_risk_level        1000 non-null   int64
 21  gender_Female                      1000 non-null   int64
 22  gender_Male                        1000 non-null   int64
 23  gender_Other                       1000 non-null   int64
 24  game_genre_Battle Royale           1000 non-null   int64
 25  game_genre_FPS                     1000 non-null   int64
 26  game_genre_MMO                     1000 non-null   int64
 27  game_genre_MOBA                    1000 non-null   int64
 28  game_genre_Mobile Games            1000 non-null   int64
 29  game_genre_RPG                     1000 non-null   int64
 30  game_genre_Strategy                1000 non-null   int64
 31  primary_game_Age of Empires        1000 non-null   int64
 32  primary_game_Apex Legends          1000 non-null   int64
 33  primary_game_CS:GO                 1000 non-null   int64
 34  primary_game_Call of Duty          1000 non-null   int64
 35  primary_game_Candy Crush           1000 non-null   int64
 36  primary_game_Civilization VI       1000 non-null   int64
 37  primary_game_Clash of Clans        1000 non-null   int64
 38  primary_game_Cyberpunk 2077        1000 non-null   int64
 39  primary_game_Dota 2                1000 non-null   int64
 40  primary_game_Elden Ring            1000 non-null   int64
 41  primary_game_Elder Scrolls Online  1000 non-null   int64
 42  primary_game_Final Fantasy XIV     1000 non-null   int64
 43  primary_game_Fortnite              1000 non-null   int64
 44  primary_game_Genshin Impact        1000 non-null   int64
 45  primary_game_League of Legends     1000 non-null   int64
 46  primary_game_Mobile Legends        1000 non-null   int64
 47  primary_game_Overwatch             1000 non-null   int64
 48  primary_game_PUBG                  1000 non-null   int64
 49  primary_game_PUBG Mobile           1000 non-null   int64
 50  primary_game_Skyrim                1000 non-null   int64
 51  primary_game_StarCraft II          1000 non-null   int64
 52  primary_game_Valorant              1000 non-null   int64
 53  primary_game_Warzone               1000 non-null   int64
 54  primary_game_World of Warcraft     1000 non-null   int64
 55  gaming_platform_Console            1000 non-null   int64
 56  gaming_platform_Mobile             1000 non-null   int64
 57  gaming_platform_Multi-platform     1000 non-null   int64
 58  gaming_platform_PC                 1000 non-null   int64
 59  mood_state_Anxious                 1000 non-null   int64
 60  mood_state_Depressed               1000 non-null   int64
 61  mood_state_Euphoric                1000 non-null   int64
 62  mood_state_Excited                 1000 non-null   int64
 63  mood_state_Irritable               1000 non-null   int64
 64  mood_state_Normal                  1000 non-null   int64
 65  mood_state_Restless                1000 non-null   int64
 66  mood_state_Withdrawn               1000 non-null   int64
dtypes: float64(10), int64(57)
memory usage: 523.6 KB