In [2]:
import pandas as pd
import numpy as np

from pprint import pprint

# models
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

In [3]:
df = pd.read_csv(
    filepath_or_buffer="work_from_home_burnout_dataset.csv"
)

In [4]:
df

      user_id day_type  ...  burnout_score  burnout_risk
0           1  Weekday  ...          19.17           Low
1           1  Weekend  ...          29.70           Low
2           1  Weekend  ...          32.93           Low
3           1  Weekday  ...          45.47           Low
4           1  Weekend  ...          51.61           Low
...       ...      ...  ...            ...           ...
1795      180  Weekend  ...          31.91           Low
1796      180  Weekend  ...          26.30           Low
1797      180  Weekend  ...          34.07           Low
1798      180  Weekday  ...          38.14           Low
1799      180  Weekend  ...          40.76           Low

[1800 rows x 11 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   user_id               1800 non-null   int64
 1   day_type              1800 non-null   object
 2   work_hours            1800 non-null   float64
 3   screen_time_hours     1800 non-null   float64
 4   meetings_count        1800 non-null   int64
 5   breaks_taken          1800 non-null   int64
 6   after_hours_work      1800 non-null   int64
 7   sleep_hours           1800 non-null   float64
 8   task_completion_rate  1800 non-null   float64
 9   burnout_score         1800 non-null   float64
 10  burnout_risk          1800 non-null   object
dtypes: float64(5), int64(4), object(2)
memory usage: 154.8+ KB

In [6]:
df["day_type"].value_counts()

day_type
Weekend    924
Weekday    876
Name: count, dtype: int64

In [7]:
mapper = {
    "Weekend": 0,
    "Weekday": 1
}

df["day_type"] = df["day_type"].map(mapper)

In [8]:
df["day_type"].value_counts()

day_type
0    924
1    876
Name: count, dtype: int64

I will firstly try to work with `burnout_risk` and then pay attention to `burnout_score`.

In [9]:
records_table = pd.DataFrame(columns=["model", "accuracy"])
records_table

Empty DataFrame
Columns: [model, accuracy]
Index: []

### Gradient Boosting Classifier

In [10]:
X = df.drop(
    columns=["user_id", "burnout_score", "burnout_risk"],
)

y = df["burnout_risk"]

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.35
)

In [12]:
X.head()

   day_type  work_hours  ...  sleep_hours  task_completion_rate
0         1        9.59  ...         7.55                  91.2
1         0        7.38  ...         6.69                  82.0
2         0        6.31  ...         8.87                  80.6
3         1        8.34  ...         8.13                  70.0
4         0        6.97  ...         5.85                  67.1

[5 rows x 8 columns]

In [13]:
y.head()

0    Low
1    Low
2    Low
3    Low
4    Low
Name: burnout_risk, dtype: object

In [14]:
gradient_boosting_classifier = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3
)

In [15]:
gradient_boosting_classifier.fit(X_train, y_train)

GradientBoostingClassifier()

In [28]:
y_pred = gradient_boosting_classifier.predict(X_test)
gbc_accuracy = np.round(accuracy_score(y_test, y_pred), 2)

In [29]:
print("Accuracy:", gbc_accuracy)

Accuracy: 0.95

In [30]:
records_table.loc[0, "model"] = 'Gradient Boosting Classifier'
records_table.loc[0, "accuracy"] = gbc_accuracy

In [31]:
records_table

                          model accuracy
0  Gradient Boosting Classifier     0.95

### Randomized Search of Best Hyperparameters

In [18]:
model = GradientBoostingClassifier()

In [19]:
param_dict = {
    "n_estimators": np.arange(100, 500, step=25),
    "learning_rate": np.linspace(0.01, 0.2, num=25),
    "max_depth": np.arange(3, 8)
}

random_search = RandomizedSearchCV(
    model,
    param_distributions=param_dict,
    n_iter=30,                       # number of random combos
    cv=5,
    scoring="accuracy",
    n_jobs=-1,
    random_state=42,
    verbose=2
)

In [20]:
random_search.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

KeyboardInterrupt:

In [ ]:
print("Best parameters:", random_search.best_params_)

Best parameters: {'n_estimators': np.int64(325), 'max_depth': np.int64(3), 'learning_rate': np.float64(0.1366666666666667)}

In [ ]:
y_pred = random_search.predict(X_test)

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9492063492063492

### Exhaustive Search of Best Hyperparameters (GridSearchCV)

In [ ]:
model = GradientBoostingClassifier()

In [ ]:
param_grid = {
    "n_estimators": np.arange(100, 500, step=25),
    "learning_rate": np.linspace(0.1, 2, num=25),
    "max_depth": np.arange(3, 8)
}

grid = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,                 # 5-fold cross validation
    scoring="accuracy",   # metric
    n_jobs=-1,            # use all CPU cores
    verbose=2
)

In [ ]:
# grid.fit(X_train, y_train)

In [ ]:
# print("Best parameters:", grid.best_params_)
# print("Best CV score:", grid.best_score_)

In [ ]:
# y_pred = grid.predict(X_test)
# print("Accuracy:", accuracy_score(y_test, y_pred))